services:
  - type: web
    name: monthly-sales-report-comparasion
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 1 --timeout 900 app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.3
